Add support for client certificate
tve/AsyncTCP pull request #1
Opened 2020-01-18 07:44 UTC by r3no1t

2020-01-21 23:09 UTC, tve requested changes
Good stuff! Two main issues:
- please make the PR against my mbed-tls-try2 branch, not master
- please revert 5755043cde55c13f8e4811f5bb1aada874345dfd in order to leave the #if ASYNC_TCL_SSL_ENABLED in the code: it saves a lot of code space for those that don't want SSL...

2020-01-21 23:09 UTC, tve commented on src/tcp_mbedtls.cpp
> +  new_item->has_client_cert = NULL;
Use false or 0, not NULL for a bool... (I know, NULL==0 but it's confusing)

2020-01-21 23:09 UTC, tve commented on src/tcp_mbedtls.cpp
> +    } TCP_SSL_DEBUG("Loading private key");
missing newline

2020-01-22 07:08 UTC, robert-alfaro commented
Is there a need to convert tcp_mbedtls.c to .cpp? Keep the externs and favor C.

2020-04-10 17:41 UTC, tve commented
nice! how did you test?

2020-04-11 19:58 UTC, r3no1t commented
Hi, I'm using it in the esphome device framework, have around 30 wifi nodes connected to an MQTT broker where I use client and server authentication.Regards,RomanAm 10.04.2020 19:41 schrieb Thorsten von Eicken <notifications@github.com>:
nice! how did you test?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

2020-04-11 20:58 UTC, tve commented
I hadn't noticed, but github says "This branch has conflicts that must be resolved" -- can you resolve them? Then I'd be happy to merge :-)

2020-04-12 16:54 UTC, r3no1t commented
sorry, my fork was not rebased, should now be ok

2020-04-12 17:52 UTC, merged

2020-04-12 17:54 UTC, tve commented
Thanks much!

2021-05-05 14:00 UTC, mrdc commented
@r3no1t 

Hi!
Will you be so kind to provide an example on how to set the client certificate & key?
`AsyncMqttClient` has only `setPsk` method, but not `setClientCert` or `setClientKey`, so it not clear how to pass it from   `AsyncClient` to `AsyncMqttClient`.

2021-05-05 18:15 UTC, r3no1t commented
@mrdc the changes on the async-mqtt-client repo are not yet merged back, so you would need the branch: https://github.com/r3no1t/async-mqtt-client/tree/add_client_certificate_support

2021-05-05 18:35 UTC, mrdc commented
@r3no1t 

Oh, thanks! I see that changes were not merged with tve's asyncmqtt repo, that's why methods are missing.

2021-05-05 19:28 UTC, mrdc commented
@r3no1t 

Unfortunately, compilation fails. I've also tried your AsyncTCP branch which was merged to tve's fork.
```
https://github.com/r3no1t/async-mqtt-client.git#add_client_certificate_support
https://github.com/r3no1t/AsyncTCP.git#add-support-for-client-certificate
```

```
.pio/libdeps/AsyncMqttClient-esphome/src/AsyncMqttClient.cpp:204:5: error: 'SSL' was not declared in this scope
     SSL* clientSsl = _client.getSSL();
     ^
.pio/libdeps/AsyncMqttClient-esphome/src/AsyncMqttClient.cpp:204:10: error: 'clientSsl' was not declared in this scope
     SSL* clientSsl = _client.getSSL();
          ^
.pio/libdeps/AsyncMqttClient-esphome/src/AsyncMqttClient.cpp:204:30: error: 'class AsyncClient' has no member named 'getSSL'
     SSL* clientSsl = _client.getSSL();
                              ^
.pio/libdeps/AsyncMqttClient-esphome/src/AsyncMqttClient.cpp:208:62: error: 'ssl_match_fingerprint' was not declared in this scope
       if (ssl_match_fingerprint(clientSsl, fingerprint.data()) == SSL_OK) {
                                                              ^
.pio/libdeps/AsyncMqttClient-esphome/src/AsyncMqttClient.cpp:208:67: error: 'SSL_OK' was not declared in this scope
       if (ssl_match_fingerprint(clientSsl, fingerprint.data()) == SSL_OK) {
```
Will check later - maybe it's because of some mess with dependencies.

2021-05-05 19:59 UTC, mrdc commented
Fix for this error when compiling for ESP32:
`#if defined (ASYNC_TCP_SSL_ENABLED) && ! defined (ASYNC_TCP_CERTIFICATE_ENABLED) && !defined(ESP32)`
https://github.com/r3no1t/async-mqtt-client/blob/178fbdb2fcd7e0ca911da04f4cbe04c9fe7ba03b/src/AsyncMqttClient.cpp#L202

2021-05-05 20:08 UTC, r3no1t commented
you just need to use these two defines when building ASYNC_TCP_SSL_ENABLED ASYNC_TCP_CERTIFICATE_ENABLED

2021-05-05 20:13 UTC, mrdc commented
@r3no1t 

Yes, the code for server fingerprint check shouldn't be used when `ASYNC_TCP_CERTIFICATE_ENABLED`, but  in my case it fails. I'll check it.

2021-05-05 21:19 UTC, mrdc commented
@r3no1t 

Maybe you know how to enable mbedTLS debug output?
With
```
#if 1
#define TCP_SSL_DEBUG(...) do { ets_printf("T %s- ", pcTaskGetTaskName(xTaskGetCurrentTaskHandle())); ets_printf(__VA_ARGS__); } while(0)
```
and 
```
build_flags = 
    -DCORE_DEBUG_LEVEL=5
```
I don't see any info related to tls...